### ISSUE TITLE
EMAIL_PORT

### ISSUE THREAD

**Issue by jahanson** [mother-of-all-self-hosting/ansible-role-authentik#1]
https://github.com/mother-of-all-self-hosting/ansible-role-authentik/blob/830eb02b9071696e6d7b546d720935aab6c1bf04/templates/env.j2#L3

If `authentik_email_port` is left unassigned it will cause an error in starting the `mash-authentik-server`.

![image](https://user-images.githubusercontent.com/1548511/233812995-b345a6e7-f93b-4087-8592-5047a0ef36ff.png)

This should be labeled as a required field or removed if not assigned.

**Comment by spantaleev** [comment]
Thanks for the report! I imagine @moan0s has not tried a default configuration with this value empty?

I think we can probably even default this to `587`.

**Comment by moan0s** [comment]
Fixed with 487e446c12a4fd934b38cf048969f51eaa92e91d
